/**
 * Created by jialiu on 16/12/20.
 */

export const CLOSE_ACTIONSHEET='qg/CLOSE_ACTIONSHEET'
export const OPEN_ACTIONSHEET='qg/OPEN_ACTIONSHEET'
export const CLOSE_MODAL='qg/CLOSE_MODAL'
export const OPEN_MODAL='qg/OPEN_MODAL'
export const CLOSE_TOAST='qg/CLOSE_TOAST'
export const OPEN_TOAST='qg/OPEN_TOAST'
export const ADD_INPUTCALLBACK='QG/ADD_INPUTCALLBACK'
export const DEL_INPUTCALLBACK='QG/DEL_INPUTCALLBACK'
export const CALL_INPUTCALLBACK='QG/CALL_INPUTCALLBACK'
export const OPEN_LOADING='QG/OPEN_LOADING'
export const CLOSE_LOADING='QG/CLOSE_LOADING'
export const OPEN_INDEXSECTION='QG/OPEN_INDEXSECTION'
export const CLOSE_INDEXSECTION='QG/CLOSE_INDEXSECTION'
export const CLOSE_ALERTIFY='qg/CLOSE_ALERTIFY'
export const OPEN_ALERTIFY='qg/OPEN_ALERTIFY'
export const OPEN_PICKER='qg/OPEN_PICKER'
export const CLOSE_PICKER='qg/CLOSE_PICKER'